server:
  port: 8083

spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance: ReactiveCrud

info:
  name: spring-boot-actuator-test
  description: springboot-admin-client-description
  version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans


