server:
  ##端口号
  port: 8080
mybatis:
  ##检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
  check-config-location: true
  ##配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  ## mapper xml 文件地址
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
