spring:
  #DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mapper:
  mappers:
      - tk.mybatis.mapper.common.Mapper
      - com.huzh.springbootmybatismapper.common.CommonMapper
  not-empty: true