spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  ##validate  加载hibernate时，验证创建数据库表结构
  ##create   每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
  ##create-drop        加载hibernate时创建，退出是删除表结构
  ##update                 加载hibernate自动更新数据库结构
  ##validate 启动时验证表的结构，不会创建表
  ##none  启动时不做任何操作
  #jpa配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
#        指定数据库引擎，用于使用事务
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#端口号（可不配置，默认为8080）
server:
  port: 8080
