spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master #\u8BBE\u7F6E\u9ED8\u8BA4\u7684\u6570\u636E\u6E90\u6216\u8005\u6570\u636E\u6E90\u7EC4,\u9ED8\u8BA4\u503C\u5373\u4E3Amaster
      strict: false #\u8BBE\u7F6E\u4E25\u683C\u6A21\u5F0F,\u9ED8\u8BA4false\u4E0D\u542F\u52A8. \u542F\u52A8\u540E\u5728\u672A\u5339\u914D\u5230\u6307\u5B9A\u6570\u636E\u6E90\u65F6\u5019\u4F1A\u629B\u51FA\u5F02\u5E38,\u4E0D\u542F\u52A8\u5219\u4F7F\u7528\u9ED8\u8BA4\u6570\u636E\u6E90.
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/dynamic_datasource_master?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0\u5F00\u59CB\u652F\u6301SPI\u53EF\u7701\u7565\u6B64\u914D\u7F6E
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/dynamic_datasource_slave?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.huzh.springbootmybatisdynamicdatasource2.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
