spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        # \u63A7\u5236\u53F0\u7BA1\u7406\u7528\u6237\u540D\u548C\u5BC6\u7801
        login-username: admin
        login-password: 123456
        # \u8BBE\u7F6E\u767D\u540D\u5355\uFF0C\u4E0D\u586B\u5219\u5141\u8BB8\u6240\u6709\u8BBF\u95EE
        allow:
        url-pattern: /druid/*
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/dynamic_datasource_master?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0\u5F00\u59CB\u652F\u6301SPI\u53EF\u7701\u7565\u6B64\u914D\u7F6E
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/dynamic_datasource_slave?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
      #\u4EE5\u4E0B\u662F\u652F\u6301\u7684\u5168\u5C40\u9ED8\u8BA4\u503C
      druid:
        # \u521D\u59CB\u8FDE\u63A5\u6570
        initial-size: 5
        # \u6700\u5C0F\u8FDE\u63A5\u6C60\u6570\u91CF
        min-idle: 10
        # \u6700\u5927\u8FDE\u63A5\u6C60\u6570\u91CF
        max-active: 20
        # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
        max-wait: 60000
        # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
        time-between-eviction-runs-millis: 60000
        # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
        min-evictable-idle-time-millis: 300000
        # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5927\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
        max-evictable-idle-time-millis: 900000
        # \u914D\u7F6E\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: -1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        share-prepared-statements: true
        filters: stat,wall # \u6CE8\u610F\u8FD9\u4E2A\u503C\u548Cdruid\u539F\u751F\u4E0D\u4E00\u81F4\uFF0C\u9ED8\u8BA4\u542F\u52A8\u4E86stat,wall
        stat:
          # \u6162SQL\u8BB0\u5F55
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          multi-statement-allow: true

# MyBatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.huzh.springbootmybatisdynamicdatasource2.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
